apiVersion: apps/v1
kind: Deployment
metadata:
  name: thringinx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: thri
        image: europe-west2-docker.pkg.dev/thri-petproject/new/thri:3
        ports:
        - containerPort: 80
