apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: thringinx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  type: LoadBalancer
status:
  loadBalancer: {}
